export const reportes = [
    {
        reportadoPor: "Carlos Ramírez",
        email: "carlos.ramirez@xcien.mx",
        reporteID: "0001",
        asunto: "Fallo en el servidor de autenticación",
        encargado: "Mariana López",
        prioridad: "Alta",
        estatus: "En proceso",
        fecha: "Hace 5 mins",
    },
    {
        reportadoPor: "Laura Sánchez",
        email: "laura.sanchez@xcien.mx",
        reporteID: "0002",
        asunto: "Error en la generación de reportes PDF",
        encargado: "Luis Torres",
        prioridad: "Media",
        estatus: "Pendiente",
        fecha: "Hace 15 mins",
    },
    {
        reportadoPor: "Jorge Hernández",
        email: "jorge.hernandez@xcien.mx",
        reporteID: "0003",
        asunto: "Problemas de acceso al sistema desde móvil",
        encargado: "Ana Velázquez",
        prioridad: "Baja",
        estatus: "Resuelto",
        fecha: "Hace 1 hora",
    },
    {
        reportadoPor: "María González",
        email: "maria.gonzalez@xcien.mx",
        reporteID: "0004",
        asunto: "Desfase en datos de facturación",
        encargado: "David Márquez",
        prioridad: "Alta",
        estatus: "En proceso",
        fecha: "Hace 25 mins",
    },
    {
        reportadoPor: "Pedro Castillo",
        email: "pedro.castillo@xcien.mx",
        reporteID: "0005",
        asunto: "No se puede actualizar perfil de usuario",
        encargado: "Sara Mejía",
        prioridad: "Media",
        estatus: "Pendiente",
        fecha: "Hace 10 mins",
    },
];